version: '3.8'
services:
  leaseweb-challenge:
    build: .
    image: leaseweb-challenge:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leaseweb_challenge
      DB_SSLMODE: disable
    depends_on:
      - postgres
    #   - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # environment:
    #   - REDIS_PASSWORD=yourpassword

  # Example Postgres service
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: leaseweb_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
    driver: local 

