CREATE TABLE servers (
    id SERIAL PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    ram VARCHAR(255) NOT NULL,
    hdd VARCHAR(255) NOT NULL,
    slocation VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);